
import { GeneratedItinerary, SafariFormData } from '../types';

export interface EmailPayload {
  to: string; // Reservations Team
  cc: string; // Client
  subject: string;
  htmlBody: string;
  attachment: Blob;
}

// Generate a professional HTML email template with inline styles
export const generateEmailHtml = (formData: SafariFormData, itinerary: GeneratedItinerary): string => {
  return `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; line-height: 1.6;">
      <div style="background-color: #8f8664; padding: 20px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0;">Safari Booking Request</h1>
      </div>
      
      <div style="padding: 20px; border: 1px solid #ddd; border-top: none;">
        <p><strong>Dear Reservations Team,</strong></p>
        <p>Please find attached the detailed itinerary proposal for the following client.</p>
        
        <h3 style="border-bottom: 2px solid #8f8664; padding-bottom: 5px; color: #5e5641;">Client Details</h3>
        <ul style="list-style: none; padding: 0;">
          <li><strong>Name:</strong> ${formData.name}</li>
          <li><strong>Email:</strong> ${formData.email}</li>
          <li><strong>Country:</strong> ${formData.country}</li>
          <li><strong>Travelers:</strong> ${formData.adults} Adults, ${formData.youngAdults} Teens, ${formData.children} Children</li>
          <li><strong>Travel Dates:</strong> Starting ${formData.startDate} (${formData.durationDays} Days)</li>
        </ul>

        ${formData.dietaryRequirements ? `<p><strong>Dietary Requirements:</strong> ${formData.dietaryRequirements}</p>` : ''}
        ${formData.specialOccasions ? `<p><strong>Special Occasion:</strong> ${formData.specialOccasions}</p>` : ''}

        <h3 style="border-bottom: 2px solid #8f8664; padding-bottom: 5px; color: #5e5641;">Trip Summary: ${itinerary.tripTitle}</h3>
        <p>${itinerary.summary}</p>
        <p><strong>Total Est. Cost:</strong> ${itinerary.totalEstimatedCost}</p>

        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <thead>
            <tr style="background-color: #f0efe6;">
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Day</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Location</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Lodge</th>
            </tr>
          </thead>
          <tbody>
            ${itinerary.schedule.map(day => `
              <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">Day ${day.day}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${day.title}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${day.accommodation}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <p style="margin-top: 20px; font-size: 14px; color: #666;">
          <em>The full detailed PDF itinerary is attached to this email.</em>
        </p>
      </div>
      
      <div style="background-color: #f9f8f4; padding: 15px; text-align: center; font-size: 12px; color: #888;">
        Generated by Custom Safari Planner AI
      </div>
    </div>
  `;
};

// Helper to convert Blob to Base64 string for API attachment
const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      const base64Content = base64String.split(',')[1];
      resolve(base64Content);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

// Helper to determine API URL based on environment
const getApiUrl = () => {
  if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    if (window.location.port !== '3000' && window.location.port !== '') {
       // Only try port 3000 if we are clearly in a local dev environment with a port (like Vite on 5173)
       return 'http://localhost:3000/api/send-email';
    }
  }
  return '/api/send-email';
};

// Real function to send email via backend proxy
export const sendSafariEmail = async (payload: EmailPayload): Promise<void> => {
  try {
    const base64Attachment = await blobToBase64(payload.attachment);
    const API_URL = getApiUrl();

    // Check if we should even try fetching
    // If we're in a browser sandbox (like AI Studio preview), localhost:3000 will fail
    if (API_URL.startsWith('http://localhost:3000') && !window.location.port) {
       console.log("Simulating email send in sandbox environment...");
       await new Promise(resolve => setTimeout(resolve, 1500));
       return;
    }

    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        to: payload.to,
        cc: payload.cc,
        subject: payload.subject,
        html: payload.htmlBody,
        attachment: {
          content: base64Attachment,
          filename: 'Safari_Itinerary.pdf'
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.message || `Server responded with ${response.status}`);
    }

    console.log("Email sent successfully via backend.");

  } catch (error: any) {
    console.warn("Email Service fetch failed, falling back to simulation:", error.message);
    // If fetch fails (likely no backend), we simulate success to avoid breaking the UX in preview
    if (error.message === 'Failed to fetch' || error.name === 'TypeError') {
       console.log("Simulated success (No backend detected).");
       await new Promise(resolve => setTimeout(resolve, 1500));
       return;
    }
    throw error;
  }
};
